# Generated by Django 3.2.13 on 2022-04-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntask',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
