# Generated by Django 3.2.13 on 2022-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoURL',
            field=models.URLField(blank=True, verbose_name='Photo URL of User'),
        ),
    ]
